[project]
name = "Kursovay"
version = "0.1.0"
description = ""
authors = [
    {name = "Admin",email = "stiker1503@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 88
target-version = ['py313']
skip-string-normalization = true


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["Kursovay"]
skip = ["build", "dist"]


[tool.mypy]
ignore_missing_imports = true
allow_untyped_defs = true
allow_untyped_calls = true